export const dockMenuItems = [
  {
    title: 'chrome',
    link: '/chrome',
    imageSrc: '/assets/svgs/chrome.svg',
    target: '',
    className: 'h-10 w-10 bg-white',
    width: 34,
    order: 1,
  },
  {
    title: 'blog',
    link: '/blog',
    imageSrc: '/assets/svgs/blog.svg',
    target: '',
    className: 'h-10 w-10 bg-white',
    order: 2,
  },
  {
    title: 'github',
    link: '/github',
    imageSrc: '/assets/svgs/github.svg',
    target: '',
    className: 'h-10 w-10 bg-white',
    width: 34,
    order: 3,
  },
  {
    title: 'note',
    link: '/note',
    imageSrc: '/assets/images/note.webp',
    target: '',
    order: 4,
  },
  {
    title: 'mail',
    link: '/mail',
    imageSrc: '/assets/images/email.webp',
    className: 'h-10 w-10 bg-white',
    target: '',
    order: 5,
  },
  {
    title: 'foto',
    link: '/foto',
    imageSrc: '/assets/images/picture.webp',
    target: '',
    order: 6,
    className: 'h-10 w-10 bg-white',
  },
  {
    title: 'setting',
    link: '/setting',
    imageSrc: '/assets/images/settings.webp',
    target: '',
    order: 7,
  },
];
