export const dockMenuItems = [
  {
    title: 'chrome',
    link: '/chrome',
    icon: 'chrome',
    className: 'h-10 w-10 bg-white',
    width: 34,
    order: 1,
  },
  {
    title: 'blog',
    link: '/blog',
    icon: 'blog',
    className: 'h-10 w-10 bg-white',
    order: 2,
  },
  {
    title: 'github',
    link: '/github',
    icon: 'github',
    className: 'h-10 w-10 bg-white',
    width: 34,
    order: 3,
  },
  {
    title: 'note',
    link: '/note',
    icon: 'note',
    order: 4,
  },
  {
    title: 'mail',
    link: '/mail',
    icon: 'mail',
    order: 5,
  },
  {
    title: 'foto',
    link: '/foto',
    icon: 'foto',
    order: 6,
    className: 'h-10 w-10 bg-white',
  },
  {
    title: 'setting',
    link: '/setting',
    icon: 'setting',
    order: 7,
  },
];
