/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export interface ApiErrorResponseDto {
  /** 에러 코드 */
  statusCode: number;
  /** 에러 메시지 */
  message: string;
  /** 에러 타입 */
  error: string;
}
