/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type PostsControllerFindAllParams = {
  /**
   * 검색어 (제목, 내용)
   */
  searchTerm?: string;
  /**
   * 태그 필터 (쉼표로 구분 가능)
   */
  tags?: string[];
  /**
   * 페이지 인덱스 (0부터 시작)
   */
  pageIndex?: number;
  /**
   * 페이지 크기
   */
  pageSize?: number;
};
