/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export interface Post {
  /** 게시글 ID (자동생성) */
  id: number;
  /** 게시글 제목 */
  title: string;
  /** 게시글 본문 내용 (마크다운 지원) */
  content: string;
  /** 썸네일 이미지 URL */
  thumbnailUrl?: string;
  /** 게시글 태그 목록 */
  tags?: string[];
  /** 게시글 생성 시간 */
  createdAt: string;
  /** 게시글 수정 시간 */
  updatedAt: string;
}
