/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export interface DeleteCommentResponseDto {
  /** 삭제 성공 여부 */
  success: boolean;
}
