/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { Post } from './post';

export interface PostsResponseDto {
  /** 게시글 목록 */
  list: Post[];
  /** 전체 게시글 수 */
  totalCount: number;
}
