/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type PostsControllerCreatePostBody = {
  /** 게시글 제목 */
  title: string;
  /** 게시글 내용 (마크다운 지원) */
  content: string;
  /** 게시글 태그 목록 */
  tags?: string[];
  /** 썸네일 이미지 파일 (jpg, jpeg, png, webp, gif) */
  thumbnail?: Blob;
};
