/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ApiErrorDtoErrors } from './apiErrorDtoErrors';

export type ApiErrorDto = {
  result: number;
  message: string;
  timestamp: string;
  path?: string;
  errors?: ApiErrorDtoErrors;
};
