/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type CommentRemoveResponseDto = {
  /** 삭제 코멘트 id */
  id: number;
};
