/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CommentResponseDtoUser } from './commentResponseDtoUser';

export type CommentResponseDto = {
  /** 댓글 ID (자동생성) */
  id: number;
  /** 댓글 내용 */
  content: string;
  /** 게시글 ID */
  postId: number;
  /** 댓글 생성 시간 */
  createdAt: string;
  /** 댓글 수정 시간 */
  updatedAt: string;
  /** 작성자 정보 */
  user: CommentResponseDtoUser;
};
