/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type DeleteImageDto = {
  /** 삭제된 이미지 URL */
  imageUrl: string;
};
