/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { CommentRemoveResponseDto } from './commentRemoveResponseDto';

export type DeleteComments200AllOf = {
  statusCode?: number;
  success?: boolean;
  data?: CommentRemoveResponseDto;
  timestamp?: string;
};
