/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * HTTP 상태 코드 또는 커스텀 에러 코드
 */
export type ErrorResponseDtoStatusCode =
  (typeof ErrorResponseDtoStatusCode)[keyof typeof ErrorResponseDtoStatusCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseDtoStatusCode = {
  NUMBER_500: 500,
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_600: 600,
  NUMBER_601: 601,
  NUMBER_602: 602,
  NUMBER_603: 603,
  NUMBER_604: 604,
  NUMBER_501: 501,
  NUMBER_502: 502,
  NUMBER_503: 503,
  NUMBER_504: 504,
  NUMBER_505: 505,
  NUMBER_506: 506,
  NUMBER_701: 701,
  NUMBER_702: 702,
  NUMBER_703: 703,
  NUMBER_704: 704,
  NUMBER_705: 705,
} as const;
