import type { ErrorResponseDtoError } from './errorResponseDtoError';
import type { ErrorResponseDtoMessage } from './errorResponseDtoMessage';
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ErrorResponseDtoStatusCode } from './errorResponseDtoStatusCode';

export type ErrorResponseDto = {
  /** HTTP 상태 코드 또는 커스텀 에러 코드 */
  statusCode: ErrorResponseDtoStatusCode;
  /** 에러 유형을 나타내는 상수 키 */
  error: ErrorResponseDtoError;
  /** 에러 상세 메시지 */
  message: ErrorResponseDtoMessage;
  /** 에러 발생 시간 */
  timestamp: string;
  /** 에러가 발생한 API 경로 */
  path?: string;
};
