/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type LoginRequestDtoPlatform =
  (typeof LoginRequestDtoPlatform)[keyof typeof LoginRequestDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginRequestDtoPlatform = {
  github: 'github',
} as const;
