/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { PostDto } from './postDto';

export type PostsResponseDto = {
  /** 게시글 목록 */
  list: PostDto[];
  /** 전체 게시글 수 */
  totalCount: number;
};
