/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { PostsTagsResponseDtoTagsItem } from './postsTagsResponseDtoTagsItem';

export type PostsTagsResponseDto = {
  /** 전체 태그 목록 및 사용 횟수 */
  tags: PostsTagsResponseDtoTagsItem[];
};
