/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type PostsRequestDto = {
  /** 현재 페이지 */
  page: number;
  /** 페이지당 게시글 수 */
  limit: number;
  /** 검색어 */
  searchTerm: string;
  /** 태그 */
  tags: string;
};
