/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type RefreshTokenRequestDtoPlatform =
  (typeof RefreshTokenRequestDtoPlatform)[keyof typeof RefreshTokenRequestDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefreshTokenRequestDtoPlatform = {
  github: 'github',
} as const;
