/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */
import type { _ } from './_';

export type RemovePosts200AllOf = {
  statusCode?: number;
  success?: boolean;
  data?: _;
  timestamp?: string;
};
