/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * COCOMOMO API
 * COCOMOMO 백엔드 API 문서
 * OpenAPI spec version: 1.0
 */

export type UpdatePostDto = {
  /** 게시글 제목 */
  title?: string;
  /** 게시글 본문 내용 */
  content?: string;
  /** 게시글 태그 목록 */
  tags?: string;
  /** 게시글 썸네일 이미지 파일 */
  thumbnail?: Blob;
};
